appName: syncstorage
namespace: syncstorage

image:
  repository: urmelausmall/syncstoragersdocker
  tag: 0.18.2
  imagePullPolicy: IfNotPresent

env:
  TZ: America/Chicago
  PGID: 568
  PUID: 568
  # Use: cat /dev/urandom | base32 | head -c64
  SYNC_MASTER_SECRET: ""
  # Use: cat /dev/urandom | base32 | head -c64
  METRICS_HASH_SECRET: ""
  SYNC_CAPACITY: 10
  LOGLEVEL: 1

ingress:
  host: syncstorage-rs.example.com

service:
  port: 8000

database:
  SYNC_SYNCSTORAGE__DATABASE_URL: mysql://user:pw@127.0.0.1:3306/ff_syncstorage
  SYNC_TOKENSERVER__DATABASE_URL: mysql://user:pw@127.0.0.1:3306/ff_tokenserver

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 4000m
    memory: 2000Mi