apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app:  {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app:  {{ .Values.appName }}
    spec:
      containers:
      - name:  {{ .Values.appName }}
        image:  "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        env:
        - name: TZ
          value: "{{ .Values.env.TZ }}"
        - name: PUID
          value: "{{ .Values.env.PUID }}"
        - name: PGID
          value: "{{ .Values.env.PGID }}"
{{ if .Values.database.external }}
        - name: DATABASE_URL
          value: "{{ .Values.database.URL }}"
{{ end }}
{{ if .Values.adminPanel.enabled }}
        - name: ADMIN_TOKEN
          value: "{{ .Values.adminPanel.token }}"
{{ end }}
{{ if .Values.email.enabled }}
        - name: SMTP_HOST
          value: "{{ .Values.email.host }}"
        - name: SMTP_FROM
          value: "{{ .Values.email.from }}"
        - name: SMTP_security
          value: "{{ .Values.email.security }}"
        - name: SMTP_USERNAME
          value: "{{ .Values.email.username }}"
        - name: SMTP_PASSWORD
          value: "{{ .Values.email.password }}"
        - name: SMTP_PORT
          value: "{{ .Values.email.port }}"
{{ end }}
        ports:
        - containerPort:  {{ .Values.service.port }}
          name:  {{ .Values.appName }}
        volumeMounts:
        - name: data
          mountPath: {{ .Values.persistence.data.mountPath }}
      volumes:
        - name: data
          hostPath:
            path: {{ .Values.persistence.data.hostPath }}
      restartPolicy: Always