apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app:  {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
  type: {{ .Values.ports.type }}
  loadBalancerIP: {{ .Values.ports.loadBalancerIP }}
  externalTrafficPolicy: Local
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: {{ .Values.appName }}
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  - name: {{ .Values.appName }}-dlna
    port: 1900
    targetPort: 1900