kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.appName }}
                port:
                  number: {{ .Values.ports.gui }}