apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app:  {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: gui
    protocol: TCP
    port: {{ .Values.ports.gui }}
    targetPort: {{ .Values.ports.gui }}
  - name: device
    protocol: TCP
    port: {{ .Values.ports.device }}
    targetPort: {{ .Values.ports.device }}
  - name: stun
    protocol: UDP
    port: {{ .Values.ports.stun }}
    targetPort: {{ .Values.ports.stun }}
  - name: discovery
    protocol: UDP
    port: {{ .Values.ports.discovery }}
    targetPort: {{ .Values.ports.discovery }}
  type: {{ .Values.ports.type }}
  loadBalancerIP: {{ .Values.ports.loadBalancerIP }}
  externalTrafficPolicy: Local
