appName: jellyfin-test
namespace: jellyfin-test

image:
  repository: nerethos/stash-jellyfin-ffmpeg
  tag: v0.27.2
  imagePullPolicy: IfNotPresent

env:
  TZ: America/Chicago
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
  PUID: 1000
  PGID: 1000

service:
  port: 9999

ingress:
  host: jellyfin-test.example.com

persistence:
  config:
    hostPath: /path/on/host
    mountPath: /config
  data:
    mountPath: /data
    existingClaim: nfs-media

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 4000m
    memory: 2000Mi
  