appName: unifi-controller
namespace: unifi-controller

image:
  repository: lumel/unifi-controller
  tag: 9.1.120
  imagePullPolicy: IfNotPresent

env:
  TZ: America/Chicago
  MEM_LIMIT: 1024
  PGID: 0
  PUID: 0

ingress:
  host: unifi.example.com

ports:
  type: LoadBalancer
  loadBalancerIP: 10.10.10.10
  gui: 8443
  device: 8080
  stun: 3478
  discovery: 10001

persistence:
  config:
    hostPath: /path/on/host
    mountPath: /usr/lib/unifi/data

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 4000m
    memory: 2000Mi