appName: actual-server
namespace: actual-server

image:
  repository: actualbudget/actual-server
  tag: 24.6.0@sha256:8f947694b2ac0b6db5b8629f2589a8f0fe7acbfa69013cf0bccb0a3131f1d8f3
  imagePullPolicy: IfNotPresent

env:
  TZ: America/Chicago
  ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB: 20
  ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB: 50
  ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB: 50
  ACTUAL_PORT: 80

ingress:
  host: budget.example.com

persistence:
  data:
    hostPath: /path/on/host
    mountPath: /data

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 4000m
    memory: 2000Mi