appName: vaultwarden
namespace: vaultwarden

image:
  repository: vaultwarden/server
  tag: 1.30.1
  imagePullPolicy: IfNotPresent

env:
  TZ: America/Chicago
  PGID: 568
  PUID: 568

adminPanel:
  enabled: true
  token: ""

ingress:
  host: vaultwarden.example.com

service:
  port: 80

persistence:
  data:
    hostPath: /path/on/host
    mountPath: /data

# If your password contains special characters, you will need to use percentage encoding.
# https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters
database:
  external: true
  URL: postgresql://user_name:user_password@db_host:5432/vaultwarden

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 4000m
    memory: 2000Mi